### ISSUE TITLE
Recurring events

### ISSUE THREAD

**Issue by mattlewis92** [mattlewis92/angular2-calendar#12]
Needs a better design than the ng1 version that will allow events to recur at any interval

**Comment by mattlewis92** [comment]
On more thought about this, it's better to always have the user implement this themselves as there's too many edge cases. Some helpers will be provided that will make this easier though.

**Comment by xMrWhite** [comment]
this is a good read about the RRULES spec thats used by most calendar APIs. Google and others sometimes have a way to output all occurrences, but its complex. https://nylas.com/blog/rrules/

**Comment by mattlewis92** [comment]
Oh nice, I didn't realise there was a proper spec for recurring events. I think the easiest way to support recurring events then is probably just to point people to the [rrule lib](https://github.com/jkbrzt/rrule) and have them generate events with that.

**Comment by mattlewis92** [comment]
Superseded by https://github.com/mattlewis92/angular2-calendar/issues/32
