### ISSUE TITLE
refactor all CSS into separate SASS files

### ISSUE THREAD

**Issue by mattlewis92** [mattlewis92/angular2-calendar#2]
Will allow all variables to be customised, plus it could potentially be shared with the ng1 version

**Comment by thomasjosephgreco** [comment]
@mattlewis92 hey matt, I could definitely work to set this up if you'd like. Would be happy to work on it so let me know your thoughts 😄

**Comment by mattlewis92** [comment]
That would be awesome! A couple of things you'll need to do to tackle this:
- [ ] setup the sass / css / style loader webpack config [like so](https://github.com/mattlewis92/angular2-tv-tracker/blob/master/webpack.config.js#L18)
- [ ] extract the existing styles into separate scss files. As the CSS classes will now be available on the global scope you'll need to scope them using sass's nesting like so:
```
.calendar-month-view { // add this class to the root element of the month view component
  .events {
  }
  ... other classes from the month view component
}
```
- [ ] the demo component should then import a sass index files which imports all the other sass files (so as not to bundle the sass files with the component source)
- [ ] extract all colors etc into variables so that they could be customised by a user of this component. Ionic does a [really good job](https://github.com/driftyco/ionic/blob/master/src/components/alert/alert.scss) of this
- [ ] for bonus points you could also setup and configure [stylelint](https://github.com/stylelint/stylelint)

**Comment by thomasjosephgreco** [comment]
@mattlewis92 sounds good man! going to work on it bit by bit today. will let you know if I have any trouble.... looking forward to lending you a hand 👍

**Comment by mattlewis92** [comment]
Great, thanks a lot! 😀

**Comment by thomasjosephgreco** [comment]
@mattlewis92 i seem to be having trouble with the sass-loader... In the meantime I can begin refactoring some of the CSS to Sass, however I am running into an error when I try to use the `styleUrls` property. Even when I try to use an external `.css` file, Angular2 can not find the code. I tried a number of different ways to fire it up so I wanted to see if you had any input as I have set up webpack's sass-loader a handful of times in the past to work with ng2. 

Let me know your thoughts!

**Comment by thomasjosephgreco** [comment]
I tried to commit a change but it seems pretty tightly knit to do so, but this was going to be my commit message: 

```
Added sass,css,style loader & configured webpack according to ng2-tv-tracker. I updated the project by adding the same dependencies that were in the ng2-tv-tracker however I still ran into an error. I am curious if this is because of how Angular2 compiles applications.
```

Additionally, I added the following dependencies to the project: `node-sass`, `sass-loader`, `css-loader`, `style-loader` as [shown here](https://github.com/mattlewis92/angular2-tv-tracker/blob/master/package.json#L26-L30), and I also added [this piece of code](https://github.com/mattlewis92/angular2-tv-tracker/blob/master/webpack.config.js#L18) as per your suggestion.

**Comment by mattlewis92** [comment]
Ah right, you don't need to use `styleUrls` on the component, I would say keep all the SASS files separate and then just `import 'main.scss'` in the demo component which will import the styles globally.

**Comment by thomasjosephgreco** [comment]
@mattlewis92 got it 👍 

This is what it is looking like now so I am about to scope all of the styles correctly and from there i'll break them into variables. 

<img width="1194" alt="screen shot 2016-07-14 at 2 28 09 pm" src="https://cloud.githubusercontent.com/assets/6646552/16850934/439c76da-49cf-11e6-83f2-0420b5f512d6.png">


I'll try and add some mixins if i find repeating patterns as well if you're down with that.

**Comment by mattlewis92** [comment]
That's awesome, glad it's coming along nicely!

**Comment by thomasjosephgreco** [comment]
I just pushed some code for this & commented on it [here](https://github.com/mattlewis92/angular2-calendar/pull/21).
