### ISSUE TITLE
Remove the calendarTitle pipe

### ISSUE THREAD

**Issue by mattlewis92** [mattlewis92/angular2-calendar#40]
Can just be replaced with the `calendarDate` pipe

**Comment by thomasjosephgreco** [comment]
hey matt, I tried to implement this quickly but I seem to be running into an error. Whenever I switch out the `calendarTitle` pipe for `calendarDate`, my console spits out this message.

```
EXCEPTION: TypeError: this.dateFormatter[method] is not a function
```

I tried a few different things but wanted to reach out and see if you had a simple solution before I really spent time digging around. Let me know !

**Comment by mattlewis92** [comment]
It's because the methods have changed. Before:
```
date | calendarTitle:'day'
```

After
```
date | calendarDate:'dayViewTitle'
```

The current calendarTitle is just a very thin wrapper that appends the `ViewTitle` string to the day view: https://github.com/mattlewis92/angular2-calendar/blob/master/src/pipes/calendarTitle.pipe.ts#L12

**Comment by thomasjosephgreco** [comment]
@mattlewis92 got it 👍 thank you for the clarification. about to push the change now
