### ISSUE TITLE
implement click / edit / delete callbacks

### ISSUE THREAD

**Issue by mattlewis92** [mattlewis92/angular2-calendar#5]

**Comment by xMrWhite** [comment]
This enhancement effects my project, i'm working on it now.

**Comment by mattlewis92** [comment]
Awesome, thanks! After some more thought on this I'd prefer this as the API as it allows greater flexibility + a smaller API surface: https://github.com/mattlewis92/angular-bootstrap-calendar/issues/386#issuecomment-231094551

**Comment by xMrWhite** [comment]
That would mean implementing the actions interface https://github.com/mattlewis92/calendar-utils/issues/1

**Comment by xMrWhite** [comment]
I'm not sure I like the way this works, I'd prefer to have a general callback for onEventClicked vs the actions array. Maybe in a tooltip actions would work.

**Comment by mattlewis92** [comment]
I think eventClicked should be it's own event (that fires when you click on the event title). The actions array should only be for edit / delete style of actions.

**Comment by mattlewis92** [comment]
Hi sorry about the late reply on this one, I've made a few small tweaks to your PR to put the actions on the same line as the event title but other than that LGTM. Thanks for the help! 👍
