### ISSUE TITLE
Please fix link in about github

### ISSUE THREAD

**Issue by sireneweb** [mattlewis92/angular2-calendar#53]
When you try to acces to https://github.com/mattlewis92/angular-bootstrap-calendar, we get an error from github "Site not found"

**Comment by mattlewis92** [comment]
As the readme says right at the top: "
Please note this is currently a WIP and not yet finished, demos, npm installation will all 404 until the first release"

**Comment by sireneweb** [comment]
Sorry for my mistake :(
