### ISSUE TITLE
How to Convert Sunday to Sun.

### ISSUE THREAD

**Issue by sakul977** [mattlewis92/angular2-calendar#58]

**Comment by mattlewis92** [comment]
You need to implement a class which extends the `CalendarDateFormatter`, and override the [`monthViewColumnHeader`](https://github.com/mattlewis92/angular2-calendar/blob/master/src/providers/calendarNativeDateFormatter.provider.ts#L16) method to return the shorter date. Then pass it to angulars DI like so `{provide: CalendarDateFormatter, useClass: MyDateFormatter}`

**Comment by sakul977** [comment]
Thank You.  
It works.
 return new Intl.DateTimeFormat(locale, { weekday: 'long' }).format(date);
 return new Intl.DateTimeFormat(locale, { weekday: 'short' }).format(date);
