### ISSUE TITLE
Animations and a bit clunky

### ISSUE THREAD

**Issue by Feather-CMS** [mattlewis92/angular2-calendar#62]
Hi, thanks for the awsome software.
The animations are a bit clunky can you confirm it is an issue or am i missing something?
Thanks once again .

**Comment by mattlewis92** [comment]
Is this on the month view slidebox? I agree that it is a bit clunky, although the animation is super simple and I'm not sure exactly what I'd do to fix it. It might be a limitation of the web animations API which angular uses to do the animation. I will do some digging and see if I can come up with something.

**Comment by Feather-CMS** [comment]
I fixed it by removing the padding and adding margin to the inner div .
Works well with me now .
http://g.recordit.co/h312an3ALD.gif

**Comment by mattlewis92** [comment]
Oh awesome, would you mind sending a PR with the change? 😄

**Comment by Feather-CMS** [comment]
Sure , will do it later on .

**Comment by mattlewis92** [comment]
Dug into this a bit more today and realised the issue is more to do with how web animations work, I don't think it's possible for me to actually fix this within this library.
