### ISSUE TITLE
Template parse errors

### ISSUE THREAD

**Issue by L0key** [mattlewis92/angular2-calendar#63]
Unable to make use of the demo in Angular2 RC5 due to exceptions such as the following:
Can't bind to 'viewDate' since it isn't a known property of 'mwl-calendar-month-view'.

> 1. If 'mwl-calendar-month-view' is an Angular component and it has 'viewDate' input, then verify that it is part of this module.
> 2. If 'mwl-calendar-month-view' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
>  ("
>         <mwl-calendar-month-view
>           *ngSwitchCase="'month'"
>           [ERROR ->][viewDate]="viewDate"
>           [events]="events"
>           [activeDayIsOpen]="activeDayIsOpen"
> "): Calendar@31:10

I can't see anything wrong with the CalendarMonthView component, so I'm at a loss as to what the issue is.

**Comment by mattlewis92** [comment]
Are you importing the CalendarModule into your apps NgModule?

**Comment by L0key** [comment]
Followed the imports and providers for NgModule on the demo app and this appears to have cleared the error.

**Comment by Stevan0102** [comment]
for anyone who found the same problem, you need to include the `demo-utlis` file as well

**Comment by Abiansh** [comment]
where do i get demo-utlis folder @Stevan0102

**Comment by Stevan0102** [comment]
Hey @Abiansh ,
`demo-utlis` is here: https://github.com/mattlewis92/angular-calendar/tree/master/demos/demo-modules/demo-utils

if you look at this demo: https://mattlewis92.github.io/angular-calendar/demos/#/kitchen-sink

in `module.ts`, there is this line:
```
import { DemoUtilsModule } from '../demo-utils/module';
```

and this:
```
imports: [
DemoUtilsModule
],
```

i inculded these, thats how it went working for me

**Comment by Abiansh** [comment]
Thanks  **@Stevan0102** . 👍    .... I got the another solution to accomplish the goal....

**Comment by Enitnelav** [comment]
Hi, i have the same error and i don't want to use demoUtils i think it can work without, have you an other solution ?
thanks

**Comment by mattlewis92** [comment]
@Enitnelav remove any component usages from your templates that start with `<mwl-demo-utils-*` and it should work ok.

**Comment by Enitnelav** [comment]
i am using `<mwl-calendar-month-view></mwl-calendar-month-view>`

**Comment by mattlewis92** [comment]
Are you including `CalendarModule.forRoot()` in your NgModule import?

**Comment by Enitnelav** [comment]
For sure 
```
/** angular modules */
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { FormsModule } from '@angular/forms';
import { HttpModule, Http } from '@angular/http';
import { RouterModule } from '@angular/router';
/** lib modules */
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { TranslateModule , TranslateLoader} from '@ngx-translate/core';
import { CookieModule } from 'ngx-cookie';
import { CalendarModule } from 'angular-calendar';
/** Renault modules */
import { CoreModule } from './core/core.module';
import { SharedModule } from './shared/shared.module';
import { LayoutModule } from './layout/layout.module';
import { GalleryModule } from './pages/gallery/gallery.module';
import { CountryModule } from './pages/country/country.module';
import { VehicleModule } from './pages/vehicle/vehicle.module';
import { WelcomeModule } from './pages/welcome/welcome.module';
import { LiveModule } from './pages/live/live.module';
/** app services */
import { YamlLoader } from './core/services/translate/yaml-loader.service';
import { HttpLoaderFactory } from './core/services/translate/http-loader-factory.service';
/** app components */
import { AppComponent } from './app.component';
/** style guide */
import { StyleGuideModule } from './pages/style-guide/style-guide.module';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule, // angular 4.0+ only
    CalendarModule.forRoot(),
    FormsModule,
    HttpModule,
    TranslateModule.forRoot({
        loader: {
          provide: TranslateLoader,
          useClass: YamlLoader,
          useFactory: HttpLoaderFactory
        }
    }),
    NgbModule.forRoot(),
    CookieModule.forRoot(),
    CoreModule,
    SharedModule,
    LayoutModule,
    GalleryModule,
    CountryModule,
    VehicleModule,
    WelcomeModule,
    StyleGuideModule,
    LiveModule,
    RouterModule.forRoot([]),
  ],
  providers: [],
  bootstrap: [AppComponent],
})
export class AppModule { }

```

**Comment by mattlewis92** [comment]
I can't see anything wrong with that, what's the exact error you're getting?

**Comment by Enitnelav** [comment]
`Unhandled Promise rejection: Template parse errors:
'mwl-calendar-month-view' is not a known element:
1. If 'mwl-calendar-month-view' is an Angular component, then verify that it is part of this module.
2. If 'mwl-calendar-month-view' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("<section class="calendar">
  [ERROR ->]<mwl-calendar-month-view></mwl-calendar-month-view>
</section>
"): ng:///LiveModule/LiveCalendarComponent.html@1:2 ; Zone: <root> ; Task: Promise.then ; Value: Error {__zone_symbol__error: Error: Template parse errors:
'mwl-calendar-month-view' is not a known element:
1. If 'mwl-calendar-……}`

**Comment by mattlewis92** [comment]
Ah right, that'll be why then. Add `CalendarModule` (without the forRoot bit) to your child components NgModule.

**Comment by Enitnelav** [comment]
Cool thanks :)
It's better but i doesn't have visual and i have this error :
`TypeError: Cannot read property 'rowOffsets' of undefined at Object.eval [as updateDirectives] (ng:///CalendarModule/CalendarMonthViewComponent.ngfactory.js:369:28) at Object.debugUpdateDirectives [as updateDirectives] `

**Comment by menomanabdulla** [comment]
`'mwl-demo-utils-date-time-picker' is not a known element:
1. If 'mwl-demo-utils-date-time-picker' is an Angular component, then verify that it is part of this module.
2. If 'mwl-demo-utils-date-time-picker' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
      </td>
      <td>
        [ERROR ->]<mwl-demo-utils-date-time-picker
          [(ngModel)]="event.start"
          (ngModelChange)="refre"): ng:///DashboardModule/EventCalendarComponent.html@152:8
'mwl-demo-utils-date-time-picker' is not a known element:
1. If 'mwl-demo-utils-date-time-picker' is an Angular component, then verify that it is part of this module.
2. If 'mwl-demo-utils-date-time-picker' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("`

i steel get this error,i use my-calendar as child component and use  CalendarModule (without the forRoot) in child components NgModule.

**Comment by mattlewis92** [comment]
`mwl-demo-utils-date-time-picker` is just a utility used for part of the demo, it's not part of this library.

**Comment by ofir94** [comment]
Hello, I'm having problems with demo-utils, I'm new in angular and I want to use this calendar, where should I copy the demo-utils directory? because It is showing me the error:
Cannot find module "../demo-utils/module"
Thanks

**Comment by cyrinegh** [comment]
hello, please where we can add demo-utils ?

**Comment by cyrinegh** [comment]
![capture](https://user-images.githubusercontent.com/27626501/37043332-ad4ff6d2-2160-11e8-98d1-4eaadf3cfdc0.PNG)
this is the error please help

**Comment by sunildipun** [comment]
@mattlewis92  i have copied the demo-utils in my project and i have created a component calendars.
It is showing me error in sources.ts inside the demo-utils.
ERROR in src/app/layout/demo-utils/sources.ts(5,12): error TS2304: Cannot find name 'require'.
src/app/layout/demo-utils/sources.ts(6,20): error TS2304: Cannot find name 'require'.
src/app/layout/demo-utils/sources.ts(12,12): error TS2304: Cannot find name 'require'.
src/app/layout/demo-utils/sources.ts(13,20): error TS2304: Cannot find name 'require'.
src/app/layout/demo-utils/sources.ts(19,12): error TS2304: Cannot find name 'require'.
src/app/layout/demo-utils/sources.ts(20,20): error TS2304: Cannot find name 'require'.
src/app/layout/demo-utils/sources.ts(26,12): error TS2304: Cannot find name 'require'.

**Comment by Rajan5496** [comment]
i have same issue with mwl-demo-utils-date-time-picker

**Comment by Rajan5496** [comment]
Uncaught Error: Template parse errors:
'mwl-demo-utils-date-time-picker' is not a known element:
1. If 'mwl-demo-utils-date-time-picker' is an Angular component, then verify that it is part of this module.
2. If 'mwl-demo-utils-date-time-picker' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
      </td>
      <td>
        [ERROR ->]<mwl-demo-utils-date-time-picker
          [(ngModel)]="event.start"
          (ngModelChange)="refre"): ng:///AppModule/CalenderComponent.html@163:8
'mwl-demo-utils-date-time-picker' is not a known element:
1. If 'mwl-demo-utils-date-time-picker' is an Angular component, then verify that it is part of this module.
2. If 'mwl-demo-utils-date-time-picker' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
      </td>
      <td>
        [ERROR ->]<mwl-demo-utils-date-time-picker
          [(ngModel)]="event.end"
          (ngModelChange)="refresh"): ng:///AppModule/CalenderComponent.html@170:8
    at syntaxError (compiler.es5.js:1694)
    at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (compiler.es5.js:12791)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (compiler.es5.js:26994)
    at compiler.es5.js:26913
    at Set.forEach (<anonymous>)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (compiler.es5.js:26913)
    at compiler.es5.js:26800
    at Object.then (compiler.es5.js:1683)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (compiler.es5.js:26799)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (compiler.es5.js:26728)

**Comment by canangok** [comment]
<img width="473" alt="Ekran Resmi 2019-05-09 02 18 30" src="https://user-images.githubusercontent.com/16053448/57414429-c4de9a00-7200-11e9-8a0a-44492bf8ee0f.png">

I could not fix the error in any way. Can you please help? 

error ;
'mwl-calendar-month-view' is not a known element:
1. If 'mwl-calendar-month-view' is an Angular component, then verify that it is part of this module.
2. If 'mwl-calendar-month-view' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.Angular


App.module.ts ;

@NgModule({
  imports: [
   .....
    CommonModule,
    FormsModule,
    NgbModalModule,
    FlatpickrModule.forRoot(),
    CalendarModule.forRoot({
      provide: DateAdapter,
      useFactory: adapterFactory
    }),
    DemoUtilsModule
  ],
  declarations: [
    ....
  ],
  schemas :[CUSTOM_ELEMENTS_SCHEMA],

})

**Comment by mattlewis92** [comment]
@canangok it looks like you're trying to use the component in a different module. So you need to import the calendar module in the same NgModule that has the component you're trying to use it in, rather than the root app module which I think you're doing,

**Comment by canangok** [comment]
did what he said but still does not work :(((

**Comment by canangok** [comment]
i did what he said but still does not work :((((

**Comment by canangok** [comment]
thank you. it was dissolved.
I'il ask you something else. I try for a long time. I can't get the start day and end of the day from This.events. I want to save this.events to the Firebase. Startday and endday values ​​are not going to database. Can you help me?

**Comment by yglin** [comment]
I've encountered the similar issue but **only in production building, i.e. `ng build --prod`, `ng serve` works just fine**
The error is:
`Can't bind to 'view' since it isn't a known property of 'button'.`
And the template which triggers this error:
```
          <button
            mat-mini-fab
            mwlCalendarToday
            [view]="view"
            [(viewDate)]="viewDate"
          >
            <mat-icon>today</mat-icon>
          </button>
```

Only **mwlCalendarToday** causes this error, other directives (mwlCalendarPreviousView, mwlCalendarNextView, mwl-calendar-day-view, etc.) works as expected.

I imported CalendarModule in my child module, which of course the same module contains the problem component.

Tried to fix it by importing CalendarModule in my child module and call CalendarModule.forRoot() in root app module, just as your suggestion for @canangok, but the error remains.

The Angular version is 9
```

Angular CLI: 9.1.12
Node: 10.19.0
OS: linux x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.12
@angular-devkit/build-angular      0.901.12
@angular-devkit/build-ng-packagr   0.901.12
@angular-devkit/build-optimizer    0.901.12
@angular-devkit/build-webpack      0.901.12
@angular-devkit/core               9.1.12
@angular-devkit/schematics         9.1.12
@angular/cdk                       9.2.4
@angular/fire                      5.4.2
@angular/flex-layout               9.0.0-beta.31
@angular/http                      7.2.16
@angular/material                  9.2.4
@angular/material-moment-adapter   9.2.4
@ngtools/webpack                   9.1.12
@schematics/angular                9.1.12
@schematics/update                 0.901.12
ng-packagr                         9.1.5
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0

```

**Comment by aryan-zargar** [comment]
Hey !
i have done all of the things that you have done in the past of this issue but i still have problems

My component Module:
`import { NgModule,CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { FlatpickrModule } from 'angularx-flatpickr';
import { CalendarModule, DateAdapter } from 'angular-calendar';
import { adapterFactory } from 'angular-calendar/date-adapters/date-fns';
import { NgbModalModule } from '@ng-bootstrap/ng-bootstrap';
import { CalendarComponent } from './calendar-st-component/calendar-st-component.component';
import { CalendarMonthModule } from 'angular-calendar';
import { CalendarMonthViewComponent } from 'angular-calendar';


@NgModule({
  imports: [
    CalendarMonthModule,
    CommonModule,
    FormsModule,
    NgbModalModule,
    FlatpickrModule.forRoot(),
    CalendarModule.forRoot({
      provide: DateAdapter,
      useFactory: adapterFactory,
    }),
    
  ],
  providers:[CalendarMonthViewComponent],
  declarations: [CalendarComponent],
  exports: [CalendarComponent],
  schemas:[
    CUSTOM_ELEMENTS_SCHEMA
  ]
})
export class CalendarStModule { }
`
my app module : 
`import { NgModule } from '@angular/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { CalendarModule, DateAdapter } from 'angular-calendar';
import { adapterFactory } from 'angular-calendar/date-adapters/date-fns';
import { CalendarStModule } from './calendar-st/calendar-st.module';
import { FlatpickrModule } from 'angularx-flatpickr';
@NgModule({
  imports: [
    CalendarStModule,
    BrowserAnimationsModule,
    FlatpickrModule.forRoot(),
    CalendarModule.forRoot({
      provide: DateAdapter,
      useFactory: adapterFactory,
    }),
  ],
  bootstrap:[]
})
export class MyModule {}`

my component TS file :
`

import {
  Component,
  ChangeDetectionStrategy,
  ViewChild,
  TemplateRef,
} from '@angular/core';
import {
  startOfDay,
  endOfDay,
  subDays,
  addDays,
  endOfMonth,
  isSameDay,
  isSameMonth,
  addHours,
} from 'date-fns';
import { Subject } from 'rxjs';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';
import {
  CalendarEvent,
  CalendarEventAction,
  CalendarEventTimesChangedEvent,
  CalendarView,
} from 'angular-calendar';
import { EventColor } from 'calendar-utils';
import { CalendarMonthViewComponent } from 'angular-calendar';
const colors: Record<string, EventColor> = {
  red: {
    primary: '#ad2121',
    secondary: '#FAE3E3',
  },
  blue: {
    primary: '#1e90ff',
    secondary: '#D1E8FF',
  },
  yellow: {
    primary: '#e3bc08',
    secondary: '#FDF1BA',
  },
};

@Component({
  selector: 'calendar-component',
  changeDetection: ChangeDetectionStrategy.OnPush,
  styles: [
    `
      h3 {
        margin: 0 0 10px;
      }

      pre {
        background-color: #f5f5f5;
        padding: 15px;
      }
    `,
  ],
  templateUrl: 'calendar-st-component.component.html',
  
})
export class CalendarComponent {

  view: CalendarView = CalendarView.Month;

  CalendarView = CalendarView;

  viewDate: Date = new Date();




  refresh = new Subject<void>();

  events: CalendarEvent[] = [
    {
      start: subDays(startOfDay(new Date()), 1),
      end: addDays(new Date(), 1),
      title: 'A 3 day event',
      color: { ...colors['red'] },
      allDay: true,
      resizable: {
        beforeStart: true,
        afterEnd: true,
      },
      draggable: true,
    },
    {
      start: startOfDay(new Date()),
      title: 'An event with no end date',
      color: { ...colors['yellow'] },
    },
    {
      start: subDays(endOfMonth(new Date()), 3),
      end: addDays(endOfMonth(new Date()), 3),
      title: 'A long event that spans 2 months',
      color: { ...colors['blue'] },
      allDay: true,
    },
    {
      start: addHours(startOfDay(new Date()), 2),
      end: addHours(new Date(), 2),
      title: 'A draggable and resizable event',
      color: { ...colors['yellow'] },
      resizable: {
        beforeStart: true,
        afterEnd: true,
      },
      draggable: true,
    },
  ];

  activeDayIsOpen: boolean = true;

  constructor(private modal: NgbModal) {}

  dayClicked({ date, events }: { date: Date; events: CalendarEvent[] }): void {
    if (isSameMonth(date, this.viewDate)) {
      if (
        (isSameDay(this.viewDate, date) && this.activeDayIsOpen === true) ||
        events.length === 0
      ) {
        this.activeDayIsOpen = false;
      } else {
        this.activeDayIsOpen = true;
      }
      this.viewDate = date;
    }
  }

  eventTimesChanged({
    event,
    newStart,
    newEnd,
  }: CalendarEventTimesChangedEvent): void {
    this.events = this.events.map((iEvent) => {
      if (iEvent === event) {
        return {
          ...event,
          start: newStart,
          end: newEnd,
        };
      }
      return iEvent;
    });

  }


  addEvent(): void {
    this.events = [
      ...this.events,
      {
        title: 'New event',
        start: startOfDay(new Date()),
        end: endOfDay(new Date()),
        color: colors['red'],
        draggable: true,
        resizable: {
          beforeStart: true,
          afterEnd: true,
        },
      },
    ];
  }

  deleteEvent(eventToDelete: CalendarEvent) {
    this.events = this.events.filter((event) => event !== eventToDelete);
  }

  setView(view: CalendarView) {
    this.view = view;
  }

  closeOpenMonthViewDay() {
    this.activeDayIsOpen = false;
  }
}

`
