### ISSUE TITLE
Can't resolve all parameters for CalendarDayView: (ChangeDetectorRef, ?)

### ISSUE THREAD

**Issue by iamyojimbo** [mattlewis92/angular2-calendar#66]
Thanks for the great work on this library and it's exactly what I need!

I do have a problem loading the library, however and I see the error:

```
Can't resolve all parameters for CalendarDayView: (ChangeDetectorRef, ?)
```

I also see this warning:

```
./~/angular2-calendar/dist/umd/angular2-calendar.js
Cannot find SourceMap 'positioning.js.map': Error: Can't resolve './positioning.js.map' in '/Users/savvas/code/tlbiolabs/node_modules/angular2-calendar/dist/umd'
 @ ./src/app/app.module.ts 14:0-94
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main
```

I have imported like so:

```
imports: [
        BrowserModule,
        CommonModule,
        CalendarModule,
        routing,
    ],
```

and providers like so:

```
providers: [
        ...
        CalendarEventTitle,
        CalendarDateFormatter,
    ],
```

Any idea where I'm going wrong?

**Comment by mattlewis92** [comment]
It looks like you don't have the Locale ID set, what version of angular are you running?

**Comment by iamyojimbo** [comment]
Yes after some digging it looked like that wasn't being injected but I've seen no docs on it really.

I am on RC-5 still. What do I need?

**Comment by mattlewis92** [comment]
Hmm it should work on RC5, but I don't have any rc5 apps to test it with, try doing {provide: LOCALE_ID, useValue: 'en'} in the module that uses the calendar. Alternatively use 0.1.x of this module until you upgrade to post rc5.

**Comment by iamyojimbo** [comment]
Thanks. I tried something similar, but do you know what exports `LOCALE_ID`?

**Comment by mattlewis92** [comment]
```
import {LOCALE_ID} from '@angular/core';
```

**Comment by mattlewis92** [comment]
Had a dig into this tonight and couldn't get it working with RC5, I think along the way I must of accidentally introduced a breaking change. My advice if `{provide: LOCALE_ID, useValue: 'en'}` doesn't work would be to use 0.1.x of this module which was definitely working with RC5, or just wait until your app has been updated to the stable version of angular.
