### ISSUE TITLE
Can't get styling applied to calendar

### ISSUE THREAD

**Issue by gh0st** [mattlewis92/angular2-calendar#71]
This is the closest I can get to applying styling following code in the demo.
![screen shot 2016-10-12 at 19 23 09](https://cloud.githubusercontent.com/assets/1195688/19334537/6576cdcc-90b1-11e6-84e6-5dfd4eddccc3.png)

The only error I'm getting in my browser is 
```
[Error] TypeError: undefined is not an object (evaluating 'window.FontAwesomeCdnConfig.asyncLoading')
	runTask (main.bundle.js:79243)
	invoke (main.bundle.js:79407)
```

I do not have an `entry.ts` but I'm using a `main.ts` inside my `src` folder. It's contents are 
```
import 'bootstrap/dist/css/bootstrap.css';
import 'font-awesome/css/font-awesome.css';
import 'angular2-calendar/dist/css/angular2-calendar.css';
import 'intl';
import 'intl/locale-data/jsonp/en';
import 'core-js';
import 'zone.js/dist/zone';
import './polyfills.ts';
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { environment } from './environments/environment';
import { AppModule } from './app/';

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule);
```

**Comment by mattlewis92** [comment]
I can't see anything that'd obviously wrong there, I suspect it's probably an issue with your build tool. What are you using? e.g. webpack, system.js etc?

**Comment by gh0st** [comment]
@mattlewis92 I'm using angular-cli which uses webpack as my build tool.

**Comment by mattlewis92** [comment]
That'd odd, it should just work with the CLI. There's definitely some other config interfering with your app though as from the screenshot you can see the optional bootstrap theme is also being included and it's not referenced in the code snippet you included.

**Comment by mattlewis92** [comment]
Ah, this is a CLI issue actually, they don't support including stylesheets in typescript config as it's non standard: https://github.com/angular/angular-cli/issues/1459

I think you need to include the stylesheet somewhere in your cli config, there was a PR referenced at the end of that issue that shows how to do it.

**Comment by kodiraj** [comment]
i am also facing the same issue.i am not getting any error
<img width="1222" alt="screen shot 2016-10-19 at 12 12 24 pm" src="https://cloud.githubusercontent.com/assets/11332035/19508176/589ff3b4-95f5-11e6-84e1-cfbe3bdd1c3c.png">

**Comment by mattlewis92** [comment]
@kodiraj you're not including the stylesheets into your app. You need this somewhere: 
```
import 'angular2-calendar/dist/css/angular2-calendar.css';
```

**Comment by JohnnyMatteus** [comment]
Just include it in angular.json and refresh the application. Because the CLI does not recognize the @import by the browser, it even loads, but the settings does not apply. I am using CLI version 6.0.x

**Comment by JohnnyMatteus** [comment]
> @kodiraj você não está incluindo as folhas de estilo em seu aplicativo. Você precisa disso em algum lugar:
> 
> ```
> import 'angular2-calendar/dist/css/angular2-calendar.css';
> ```

I made this configuration in angular.json and it worked

**Comment by kaleu50** [comment]
The same error in 2019

**Comment by kaleu50** [comment]
Solved editing angular.json

```
            "styles": [
              "src/styles.css",
              "node_modules/angular-calendar/scss/angular-calendar.scss" // <--- add this
            ],
```

**Comment by moytho** [comment]
Same thing here. Just added this css file into my angular.json styles section `"styles": [
							"styles/index.scss",
							"./node_modules/angular-calendar/css/angular-calendar.css"
						],`

**Comment by Manoj-Khadka** [comment]
include the CSS file in the global (not component scoped) styles of your app:

/* angular-cli file: src/styles.css */
@import "../node_modules/angular-calendar/css/angular-calendar.css";

**Comment by Shabaltasov** [comment]
> include the CSS file in the global (not component scoped) styles of your app:
> 
> /* angular-cli file: src/styles.css */ @import "../node_modules/angular-calendar/css/angular-calendar.css";

Hi, I have error :
Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Package path ./css/angular-calendar.css is not exported from package ...\node_modules\angular-calendar (see exports field in ...\node_modules\angular-calendar\package.json)

I include the CSS file in the global styles of my app:
@import "../node_modules/angular-calendar/css/angular-calendar.css";

In angular.json I alreadyhave this style
"styles": [
              "node_modules/angular-calendar/css/angular-calendar.css",
              "projects/business-slick-estimates/src/styles.scss"
            ],
PLease, tell me how to fix it.

**Comment by Shabaltasov** [comment]
> > include the CSS file in the global (not component scoped) styles of your app:
> > /* angular-cli file: src/styles.css */ @import "../node_modules/angular-calendar/css/angular-calendar.css";
> 
> Hi, I have error : Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js): HookWebpackError: Module build failed (from ./node_modules/css-loader/dist/cjs.js): Error: Package path ./css/angular-calendar.css is not exported from package ...\node_modules\angular-calendar (see exports field in ...\node_modules\angular-calendar\package.json)
> 
> I include the CSS file in the global styles of my app: @import "../node_modules/angular-calendar/css/angular-calendar.css";
> 
> In angular.json I alreadyhave this style "styles": [ "node_modules/angular-calendar/css/angular-calendar.css", "projects/business-slick-estimates/src/styles.scss" ], angular/cli: "^15.2.7"
> 
> PLease, tell me how to fix it.

___
I got away from the problem of connecting styles and added a line
<link href="https://unpkg.com/angular-calendar@0.20.0/dist/css/angular-calendar.css" rel="stylesheet">
in my component template
I’m not sure about the optimality and correctness of this solution, so I’ll wait for your answers and comments, thx

**Comment by Jayagopal-web** [comment]
> > > include the CSS file in the global (not component scoped) styles of your app:
> > > /* angular-cli file: src/styles.css */ @import "../node_modules/angular-calendar/css/angular-calendar.css";
> > 
> > 
> > Hi, I have error : Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js): HookWebpackError: Module build failed (from ./node_modules/css-loader/dist/cjs.js): Error: Package path ./css/angular-calendar.css is not exported from package ...\node_modules\angular-calendar (see exports field in ...\node_modules\angular-calendar\package.json)
> > I include the CSS file in the global styles of my app: @import "../node_modules/angular-calendar/css/angular-calendar.css";
> > In angular.json I alreadyhave this style "styles": [ "node_modules/angular-calendar/css/angular-calendar.css", "projects/business-slick-estimates/src/styles.scss" ], angular/cli: "^15.2.7"
> > PLease, tell me how to fix it.
> 
> I got away from the problem of connecting styles and added a line link href="https://unpkg.com/angular-calendar@0.20.0/dist/css/angular-calendar.css" rel="stylesheet" in my component template I’m not sure about the optimality and correctness of this solution, so I’ll wait for your answers and comments, thx

Did you able to solve problem? I'm using Angular 18 facing same problem

`X [ERROR] Could not resolve "../node_modules/angular-calendar/css/angular-calendar.css"

    src/styles/styles.scss:5:8:
      5 │ @import "../node_modules/angular-calendar/css/angular-calendar.css";
        ╵         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

**Comment by Shabaltasov** [comment]
Hi, thanks to your response. I've already fixed it.

сб, 3 авг. 2024 г. в 07:21, JAYAGOPAL ***@***.***>:
