### ISSUE TITLE
Weekview with hour and change time range

### ISSUE THREAD

**Issue by mickeychu** [mattlewis92/angular2-calendar#72]
Is there anyway I can change the weekview to display hour as in Version for angular 1 (`calendarConfig.showTimesOnWeekView = true;`)

And if I want to change the time range from 6.00 to 21.00, what should I do?

Thank you!

**Comment by mattlewis92** [comment]
I won't be supporting the alternative week view on the angular 2 version of this calendar, there were too many issues with it from a maintenance and usability point of view. I think something like this would be better suited as a standalone library that someone else builds that complements this library.

To change the day view time range you want the dayHourStart and dayEndStart options: https://mattlewis92.github.io/angular2-calendar/docs/classes/calendardayviewcomponent.html#daystarthour
