### ISSUE TITLE
caldenar is not being rendered.

### ISSUE THREAD

**Issue by kodiraj** [mattlewis92/angular2-calendar#73]
i added the following line in my module

module.ts
import { CalendarModule }  from 'angular2-calendar/dist/esm/src';
CalendarModule.forRoot(),

in  my component

i replaced the whole demo.component.ts

attached my sample module and component.ts

the caldenar is not working over there

[Archive.zip](https://github.com/mattlewis92/angular2-calendar/files/538024/Archive.zip)

**Comment by kodiraj** [comment]
<img width="1222" alt="screen shot 2016-10-19 at 12 12 24 pm" src="https://cloud.githubusercontent.com/assets/11332035/19508195/754f372c-95f5-11e6-8d4a-5fb58491c6fe.png">

**Comment by kodiraj** [comment]
attached
<img width="1048" alt="screen shot 2016-10-19 at 12 14 14 pm" src="https://cloud.githubusercontent.com/assets/11332035/19508219/967f3488-95f5-11e6-93e8-d162976502aa.png">



attached the debugg content from the chrome console.

Basically "mwl-calendar-month-view" selector is not rendered at all.

Note:
Just to brief,i am using ng2-admin to do the development.

**Comment by mattlewis92** [comment]
It looks like it is being rendered, the `mwl-calendar-month-view` element is just collapsed in your console.

I think you're just not importing the stylesheets correctly, this looks wrong:
`styles: [('./angular2-calendar/dist/css/angular2-calendar.css')]`

If using the angular CLI you need to add `angular2-calendar/dist/css/angular2-calendar.css` somewhere in your cli config

**Comment by mcgri** [comment]
Just a note from me:

I had the same problem. I am using system.js. I copied styles to my Component's css and had the same problem. For me, it was because of the way how angular works with CSS. By default style's will be applied to the current component only.

so an easy fix, is to change default ViewEncapsulation:
`    styleUrls: ["css/style.css"],
    encapsulation: ViewEncapsulation.None`

**Comment by mattlewis92** [comment]
I wouldn't recommend importing the CSS via angular and instead just import it via something like this: https://github.com/systemjs/plugin-css

Then just do
`import 'angular2-calendar/dist/css/angular2-calendar.css'`

**Comment by mcgri** [comment]
For me , more plugins is more headache :D
Angular's css import  works like a charm for me

`    moduleId: currentPath,` 
 `    selector: 'calendar',` 
 `    templateUrl: 'templates/calendar.html',` 
    ` styleUrls: ["css/style.css"],` 
    ` encapsulation: ViewEncapsulation.None`

But we all have different setups.

**Comment by mattlewis92** [comment]
Fair enough, each to their own :)

Kind regards,
Matt Lewis

**Comment by manish786786** [comment]
i am not able to get data in day view . can anybody help me regard this
