### ISSUE TITLE
date-fns issue

### ISSUE THREAD

**Issue by MyTotoro** [mattlewis92/angular2-calendar#76]
Just trying to implement your demo

My WebStorm looks like this:

![image](https://cloud.githubusercontent.com/assets/3621921/19671487/13a7a490-9a3d-11e6-822a-6936b6f491c6.png)

but I get a 404 for date-fns

![image](https://cloud.githubusercontent.com/assets/3621921/19671496/26285a06-9a3d-11e6-80cf-8ced335f9708.png)

I'm still new to Angular2 was wondering if there was something I could do differently in the source code for the demo or did I misconfigure my Angular 2 install? Thanks!

**Comment by mattlewis92** [comment]
It looks like you're using system.js, configuring it to work with date-fns is currently a bit of a pain, there is an example here that shows how to work around things:

https://github.com/mattlewis92/angular2-calendar/tree/master/examples/systemjs

Once this lands: https://github.com/date-fns/date-fns/pull/249 you will then be able to just:
```
import {startOfMonth} from 'date-fns';
```

Personally I would recommend not using system.js though and instead go with a webpack solution via [the CLI](https://github.com/angular/angular-cli) as there is far less config involved (plus it's much faster)

**Comment by mattlewis92** [comment]
The PR just landed, so as long as you use 1.9.0+ of `date-fns` and configure your system config like this: https://github.com/mattlewis92/angular2-calendar/blob/master/examples/systemjs/systemjs.config.js it should then just work.
