### ISSUE TITLE
24-hour clock

### ISSUE THREAD

**Issue by theunreal** [mattlewis92/angular2-calendar#78]
Is it possible to change the time and clock of the calendar to 24-hour clock format?

For example:

13:00 instead 1PM

23:00 instead of 11PM

**Comment by mattlewis92** [comment]
You can use DI to handle this:
```
import {CalendarNativeDateFormatter, DateFormatterParams, CalendarModule} from 'angular2-calendar';

class CustomDateFormatter extends CalendarNativeDateFormatter {
  
  public dayViewHour({date, locale}: DateFormatterParams): string {
    // change this to return a different date format
    return new Intl.DateTimeFormat(locale, {hour: 'numeric'}).format(date);
  }

}

@NgModule({
  import: [CalendarModule],
  providers: [
    CalendarEventTitleProvider, 
     {provide: CalendarDateFormatter, useClass: CustomDateFormatter}
  ]
})
class ModuleThatUsesTheCalendar{}

```

**Comment by eliortabeka** [comment]
Hi @mattlewis92, Can you please help me to implement this? I can't get it to work..
http://plnkr.co/edit/Jqz6XJ8XYgzAxkXQG2Ax

**Comment by mattlewis92** [comment]
It seems like you need to force the locale to make this work, using canadian seems to do the trick: http://plnkr.co/edit/INtKoU2Tony08Soqy8x7?p=preview

**Comment by eliortabeka** [comment]
@mattlewis92 Thank you for the fast response!

**Comment by eliortabeka** [comment]
@mattlewis92, One more thing please - why I don't see the events in the Calendar .. ?
http://plnkr.co/edit/8rUSfzcCWBcf8LYpT0qi?p=preview

**Comment by mattlewis92** [comment]
There was no color set on each event (check the console output in your plunker). TS should complain about the missing properties in a real app though. http://plnkr.co/edit/b4fbs11FBOeldGifjmpt?p=preview

**Comment by eliortabeka** [comment]
@mattlewis92 You are rock 👍  Thanks

**Comment by Megamind2301** [comment]
Error in importing CalendarEventTitleProvider in my case.

**Comment by Dquaglio** [comment]
Did something change from the last plunker? 
```
    CalendarModule.forRoot({
      dateFormatter: {
        provide: CalendarDateFormatter, 
        useClass: CustomDateFormatter
      }
    }),
```
Gives me "Argument of type '{ dateFormatter: { provide: typeof CalendarDateFormatter; useClass: typeof CustomDateFormatter; }...' is not assignable to parameter of type 'Provider'.   Object literal may only specify known properties, and 'dateFormatter' does not exist in type 'Provider'."

**Comment by harsh-khandelwalcs** [comment]
@mattlewis92 
I need to show only from 09:00 to 17:00 hours in day view?
how can I achieve this?

**Comment by JustinDuchow01** [comment]
@harsh-khandelwalcs i think you can use daystartHour and dayEndHOur Attribute of the Calendar so for example:

```
<mwl-calendar-day-view
                            [viewDate]="viewDate"
                            [events]="events"
                            [locale]="locale"
                            [weekStartsOn]="startWeek"
                            [dayStartHour]="9"
                            [dayEndHour]="17">
    </mwl-calendar-day-view>
```

That would be a day view only from 09:00 to 17:00 hours

**Comment by stefanzugal** [comment]
Elegant solution, thank you very much!

For >= angular 9, the `CustomDateFormatter` should have a `@Injectable()` annotation - for >= angular 10, it must have the annotation.

**Comment by bbmattieu9** [comment]
@Everyone Hi, How can I add an event with startTime as 10:25PM and endTime as 11:15PM, then plot it on the calendar day view to show that exact time on the calendar as an event. The view is in THIS format. i.e 1PM = 13:00

**Comment by Simran-Satpute-964** [comment]
> You can use DI to handle this:
> 
> ```
> import {CalendarNativeDateFormatter, DateFormatterParams, CalendarModule} from 'angular2-calendar';
> 
> class CustomDateFormatter extends CalendarNativeDateFormatter {
> 
>   public dayViewHour({date, locale}: DateFormatterParams): string {
>     // change this to return a different date format
>     return new Intl.DateTimeFormat(locale, {hour: 'numeric'}).format(date);
>   }
> 
> }
> 
> @NgModule({
>   import: [CalendarModule],
>   providers: [
>     CalendarEventTitleProvider, 
>      {provide: CalendarDateFormatter, useClass: CustomDateFormatter}
>   ]
> })
> class ModuleThatUsesTheCalendar{}
> ```

I have angular-calendar instead of angular2-calendar. In my case this solution is not working. does this feature work with angular-calendar?

**Comment by mcbashie** [comment]
@tbelmega 

I tried to follow your instructions but am having trouble with the 
I've added the  [locale]="nl-NL"  into the html on the mwl-calendar-week-view.
And 'registerLocaleData(localeNL);' was already present in the app.module. 

The calendar is now only showing 00 - 23 instead of 00:00 - 23:00.
Am I right in thinking that I need a localeNlExtra to get the minutes?
How/where can I define that parameter?

**Comment by tbelmega** [comment]
@mcbashie 
My solution doesn't help you there. `CalendarNativeDateFormatter` displays only hours, not minutes, and I'm fine with that. I just wanted to localize the format for Germany, so that it shows "13 Uhr" instead  of "1 PM". `CalendarNativeDateFormatter` can do that out of the box, that's what I showed.

If you want a different format, you can create your own date formatter and provide it instead of the CalendarNativeDateFormatter. Follow [this answer](https://github.com/mattlewis92/angular-calendar/issues/78#issuecomment-256573939) my mattlewis92, but instead of `new Intl.DateTimeFormat(locale, {hour: 'numeric'})` provide your own DateTimeFormat.
Let me take a wild guess, `new Intl.DateTimeFormat(locale, {hour: 'numeric', minute: 'numeric'})` should do the trick? But you better check [the docs of Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat)

**Comment by mcbashie** [comment]
@tbelmega 
Thank you! That worked. 
Also thanks for the link to Intl.DateTimeFormat. 

I also realized I had to add weekViewHour as well besides the dayViewHour.

**Comment by MiriamTheFox** [comment]
@tbelmega 
Hey, can you explain a bit more WHERE you would put the code? I read quite often "Yeah, just add X and Y" and I am not a full-time frontend dev and wonder "Okay, nice ... uhm where?". I, for instance, added [this code from the dependency injection](https://github.com/mattlewis92/angular-calendar/issues/78#issuecomment-256573939) but sadly nothing changed. Does it need any kind of connection with the component? Is doing this stuff in the module rly everything there is?

**Comment by tbelmega** [comment]
@MiriamTheFox it depends wether your app is organized in modules or standalone components. All our answers where from a time before Angular had standalone, everything had to be in a module, that's why we didn't mention it. Nowadays standalone is the default for components.

if your component is standalone, you add the providers to the component declarations in your `my-component.ts` file:
```
@Component({
  selector: 'app-my-component',
  standalone: true,
  providers:  [ // inserted my code here
    {provide: CalendarDateFormatter, useClass: CalendarNativeDateFormatter}
  ],
  imports: [
    MatIcon, // random imports for example
    MatIconButton,
  ],
  templateUrl: './my.component.html',
  styleUrl: './my.component.scss'
})
export class MyComponent {
// ...
}
```

On the other hand, if your component is part of a module, then you add the provider to the module file like  `my-module.ts`:

```
@NgModule({
  import: [CalendarModule],
  declarations: [
    MyComponent, // this makes MyComponent part of MyModule. MyComponent is NOT standalone
  ],
  providers: [
     // this makes CalendarNativeDateFormatter being used by all components in this module
    {provide: CalendarDateFormatter, useClass: CalendarNativeDateFormatter}
  ]
})
class MyModule{
  // ....
}
```

**Comment by MiriamTheFox** [comment]
@tbelmega:
Then everything was already where it belonged. Sadly, `locale, {hour: 'numeric', minute: 'numeric'}` did not only not change it to xx:00, it changed absolutely nothing at all. Guess I just try sth completely different. Still thank you very much for the response.

**Comment by tbelmega** [comment]
If you can share your entire project on GitHub, let me know, I'm happy to give it a look. I agree it's sometimes very complicated to configure stuff correctly to make it work, I've been struggling as well a couple of times...

**Comment by MiriamTheFox** [comment]
@tbelmega:
Oh Lawd. I furiously did it all over again and copy-pasted code. Turned out I copied your `... useClass: CalendarNativeDateFormatter` but still had mattlewis' `class CustomDateFormatter extends ...` in my DI ... ** fail **

**Comment by incodenet** [comment]
Living this code snippet for someone who will face this problem in future:

angular-calendar v0.32.2

```
import { Injectable } from '@angular/core';
import {
  DateFormatterParams,
  CalendarDateFormatter,
} from 'angular-calendar';
import {
  formatDate,
} from 'date-fns';

@Injectable()
export class CustomDateFormatter extends CalendarDateFormatter {
  override weekViewHour({ date, locale }: DateFormatterParams): string {
    return formatDate(date, 'HH:mm');
  }

  override dayViewHour({ date, locale }: DateFormatterParams): string {
    return formatDate(date, 'HH:mm');
  }
}
```

and inside @Component or @Module:

```
 providers: [
    provideCalendar({
      provide: DateAdapter,
      useFactory: adapterFactory,
    }),
    {
      provide: CalendarDateFormatter,
      useClass: CustomDateFormatter,
    },
  ],
```
