### ISSUE TITLE
allDay event disappear

### ISSUE THREAD

**Issue by Bigismall** [mattlewis92/angular2-calendar#79]
In Day View,  _allDay_ event is not shown, when `dayStartHour > 0` 

Ex.  `dayStartHour="6"`

I'm sure it's because of position calculations default from 0 hour.

**Comment by mattlewis92** [comment]
Good catch! I'll get that fixed in the next release, thanks for reporting 😄

**Comment by xibriz** [comment]
Was this fixed? I'm having the same issue with version `angular-calendar@0.26.11`
