### ISSUE TITLE
Operations on event array doesn't reflect on the calendar ?

### ISSUE THREAD

**Issue by andreroggeri** [mattlewis92/angular2-calendar#82]
Hi, array operations on event object doesn't reflects on Calendar component.

For example: pushing or poping elements from event array and the Calendar isn't updated.

Is this a expected behavior ?

**Comment by mattlewis92** [comment]
This is expected as angular doesn't deep watch array inputs for changes (for performance reasons). You have a few options to work around this. You can either create a new array reference which will trigger off change detection like so:
```
this.events = [...this.events];
OR
this.events = Array.from(this.events);
```

or pass an observable to the `refresh` input and emit on it to cause the calendar to refresh. There is a test that demonstrates that here: https://github.com/mattlewis92/angular2-calendar/blob/master/test/calendarMonthView.component.spec.ts#L177-L196

Hope that helps!
