### ISSUE TITLE
incorrect left margin for day event

### ISSUE THREAD

**Issue by Bigismall** [mattlewis92/angular2-calendar#83]
After update to 0.3.6 i have another issue with displaying day events.
It seems to JS concat strings, and position of event is huge :)  So this mean that  event properties are treated  as strings

![snip_20161031064520](https://cloud.githubusercontent.com/assets/3478892/19848134/b43f6e66-9f4b-11e6-81c0-495d97b6f743.png)

I'll do an investigation. In demo 0.3.6 everything is fine. I did diff with my custom version, but couldn't see nothing.  I'm using Polish locale  `import 'intl/locale-data/jsonp/pl-PL';`  and that's only difference with official version.

Till this time, maybe someone has na idea why is JS  treat day event properties as strings.

**Comment by mattlewis92** [comment]
I think the issue is with your day view, the option `eventWidth="150"` is treated as a string, and should be `[eventWidth]="150"`

**Comment by Bigismall** [comment]
it's not this :(

`  template: `
    <div
      class="cal-event mdl-list"
      [style.marginTop.px]="dayEvent.top"
      [style.marginLeft.px]="dayEvent.left + 70"
      [style.height.px]="dayEvent.height"
      [style.width.px]="dayEvent.width - 1"
      [style.backgroundColor]="dayEvent.event.color.secondary"
      [style.borderColor]="dayEvent.event.color.primary"
      [class.cal-starts-within-day]="!dayEvent.startsBeforeDay"
      [class.cal-ends-within-day]="!dayEvent.endsAfterDay"
      [ngClass]="dayEvent.event.cssClass">
      <div class="mdl-list__item">
      <mwl-calendar-event-title
        [event]="dayEvent.event"
        view="day"
        (click)="eventClicked.emit()"
        class="mdl-list__item-primary-content">
      </mwl-calendar-event-title>
      <mwl-calendar-event-actions 
      [event]="dayEvent.event" 
      class="mdl-list__item-secondary-action">
      </mwl-calendar-event-actions>
      </div>
    </div>
  ``

but i'll investigate it  :)

**Comment by mattlewis92** [comment]
If you can make a runnable repo that reproduces the issue I'm happy to dig in and try and see what's going wrong :)

**Comment by Bigismall** [comment]
ok,  if I can not find fault, i'll setup my own demo version for you

**Comment by Bigismall** [comment]
I Found!
When i saw your last changes  in calendar-utils 
https://github.com/mattlewis92/calendar-utils/commit/d0f4ce020b959edd36834c75a0ce3bc5f511748b

i was wonder what will it produce after conversion to JS  so i took a look at 

C:\DEV\calendar.localhost\node_modules\calendar-utils\dist\src\calendarUtils.js

and i saw 

```
        var left = 0;
        while (overlappingPreviousEvents.some(function (previousEvent) { return previousEvent.left === left; })) {
            left += eventWidth;
        }

```

after change to  (parseInit)

```
        var left = 0;
        while (overlappingPreviousEvents.some(function (previousEvent) { return previousEvent.left === left; })) {
            left += parseInt(eventWidth);
        }

```

my calendar looks fine

**Comment by mattlewis92** [comment]
I thought that might be why, `eventWidth` should always be a number, how are you passing it through?

**Comment by Bigismall** [comment]
```

<mwl-calendar-day-view
          *ngSwitchCase="'day'"
          [viewDate]="viewDate"
          [events]="events"
          eventWidth="250"
          locale="pl-PL"
          hourSegments="2"
          dayStartHour="6"
          dayEndHour="21">
        </mwl-calendar-day-view>


```

**Comment by mattlewis92** [comment]
`eventWidth="250"` should be `[eventWidth]="250"`, otherwise angular treats it as a string. Probably the same for the other numeric bindings as well

**Comment by Bigismall** [comment]
so True!
