### ISSUE TITLE
Is localization possible?

### ISSUE THREAD

**Issue by derdasmachenmuss** [mattlewis92/angular2-calendar#84]
Is there a way to localize the calendar? In detail, I want set Monday to be the first day of week and to change the day's names.

**Comment by mattlewis92** [comment]
Yup localisation is possible through these 2 options:
https://mattlewis92.github.io/angular2-calendar/docs/classes/calendarmonthviewcomponent.html#locale
https://mattlewis92.github.io/angular2-calendar/docs/classes/calendarmonthviewcomponent.html#weekstartson
