### ISSUE TITLE
Allow events to be resized

### ISSUE THREAD

**Issue by mattlewis92** [mattlewis92/angular2-calendar#9]
- [x] week view
- [x] day view

**Comment by mattlewis92** [comment]
Also need to allow the user to validate each resize

**Comment by RamitAnandSharma** [comment]
Hi Guys thanks for creating this library.  
I need event resizing feature in my project. When this feature will available for use.

**Comment by lakfa** [comment]
Hello and thanks for creating this library
The problem I have is that events can't be resizable when am passing a custom event template
```
<ng-template #eventTemplate let-weekEvent="weekEvent" let-locale="locale">
  <div class="event-template">
    <i
      class="pi pi-calendar pi-lg"
      style="font-size: 12px; background-color: #7fff00"
    >
      <span style="font-weight: bold; font-size: 11px">
        {{ weekEvent.event.title }}
      </span>
    </i>
    <p>{{ weekEvent.event?.meta?.subTitle }}</p>
  </div>
</ng-template>
```
I guess I need to implement resize feature my self but I don't know how
Thanks for your help

**Comment by miradofitiavana** [comment]
> Hello and thanks for creating this library The problem I have is that events can't be resizable when am passing a custom event template
> 
> ```
> <ng-template #eventTemplate let-weekEvent="weekEvent" let-locale="locale">
>   <div class="event-template">
>     <i
>       class="pi pi-calendar pi-lg"
>       style="font-size: 12px; background-color: #7fff00"
>     >
>       <span style="font-weight: bold; font-size: 11px">
>         {{ weekEvent.event.title }}
>       </span>
>     </i>
>     <p>{{ weekEvent.event?.meta?.subTitle }}</p>
>   </div>
> </ng-template>
> ```
> 
> I guess I need to implement resize feature my self but I don't know how Thanks for your help

Hello @lakfa, did you find how to resize when it is a custom template ?
